- name: Pre-Setup
  hosts: all
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Remove unnecessary packages
      apt:
        name:
          - snapd
          - lxd-agent-loader
          - command-not-found
          - python3-commandnotfound
          - apport
          - apport-core-dump-handler
          - apport-symptoms
          - python3-apport
          - open-iscsi
          - multipath-tools
          - motd-news-config
          - landscape-common
          - ubuntu-pro-auto-attach
          - ubuntu-pro-client
          - ubuntu-pro-client-l10n
        state: absent
        purge: yes

    - name: Install required packages
      apt:
        name:
          - curl
          - cloud-init
        state: present

    - name: Configure unattended-upgrades for security updates only
      copy:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        content: |
          Unattended-Upgrade::Origins-Pattern {
              "o=Ubuntu,a=${distro_codename}-security";
          };
          Unattended-Upgrade::Package-Blacklist {
          };
          Unattended-Upgrade::Automatic-Reboot "false";
          Unattended-Upgrade::MinimalSteps "true";
          Unattended-Upgrade::Remove-Unused-Dependencies "true";

    - name: Enable unattended-upgrades
      copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Unattended-Upgrade "1";
          APT::Periodic::AutocleanInterval "7";

    - name: Disable root SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "PermitRootLogin no"
        state: present

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
