- name: Setup Firewall
  hosts: all
  become: yes

  tasks:
    - name: Allow OpenLiteSpeed WebAdmin port
      ufw:
        rule: allow
        port: "7080"
        proto: tcp

    - name: Allow HTTP and HTTPS traffic
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - "80"
        - "443"

    - name: Allow SSH
      ufw:
        rule: allow
        port: ssh
        proto: tcp

    - name: Enable UFW firewall
      ufw:
        state: enabled
