- name: Setup OpenLiteSpeed and PHP
  hosts: all
  become: yes
  vars:
    php_version: "83"

  tasks:
    - name: Add OpenLiteSpeed repository
      shell: |
        wget -O - https://repo.litespeed.sh | bash
      args:
        executable: /bin/bash

    - name: Install OpenLiteSpeed
      apt:
        name: openlitespeed
        state: present
        update_cache: yes

    - name: Install LSPHP 8.1
      apt:
        name:
          - lsphp{{ php_version }}
          - lsphp{{ php_version }}-common
          - lsphp{{ php_version }}-imap
          - lsphp{{ php_version }}-mysql
          - lsphp{{ php_version }}-opcache
        state: present

    - name: Create a symbolic link for PHP
      file:
        src: /usr/local/lsws/lsphp{{ php_version }}/bin/php
        dest: /usr/bin/php
        state: link

    - name: Enable and start OpenLiteSpeed
      systemd:
        name: lsws
        enabled: yes
        state: started
